name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build extension
        run: make extension
        env:
          DOCKER_BUILDKIT: 1
